### ISSUE TITLE
Support for OpenRouter

### ISSUE THREAD

**Issue by adrm** [joshpxyne/gpt-migrate#39]
It would be great to use other GPT-like API endpoints like [OpenRouter](https://openrouter.ai/). For example, this would allow anyone to use gpt-4-32k even if they have no access from their OpenAI accounts, since OpenAI is no longer giving access to gpt-4-32k for the time being, and this model is basically a requisite to use gpt-migrate.

**Comment by krrishdholakia** [comment]
Hey @adrm gpt-migrate should already have support for this through using litellm 

https://docs.litellm.ai/docs/providers/openrouter

https://github.com/joshpxyne/gpt-migrate/blob/8f6dfdd45096716aa078fcd659e50aa04b44fec7/gpt_migrate/ai.py#L23

**Comment by UMR-Pleasant** [comment]
@krrishdholakia 
Can you give any details on how to actually do this? (that is, what command line parameters + environment variables need to be set, any code needs to be modified, if any etc.)

**Comment by LyleRolleman-plst** [comment]
Ok, found my problem. Turns out the version of litellm in requirements.txt does not support openrouter (too old)

pip install --upgrade litellm and it was able to recognize the openrouter model passed in (openrouter/openai/gpt-4-32k)

**Comment by joshpxyne** [comment]
Added OpenRouter
