### ISSUE TITLE
Invalid response object from API: 'Request Entity Too Large' (HTTP response code was 413) with openrouter gpt-4-32k

### ISSUE THREAD

**Issue by nickvarterian** [joshpxyne/gpt-migrate#44]
I am encountering an error when using the openrouter gpt-4-32k API. The error message I'm receiving is as follows:

Invalid response object from API: 'Request Entity Too Large\n\nFUNCTION_PAYLOAD_TOO_LARGE\n' (HTTP response code was 413)

The HTTP response code associated with this error is 413. It appears that the issue is related to the size of the prompt being sent to the openrouter API, as it is too large.

The prompt that is created by gpt-migrate is too large for openrouters api. Has anyone ran into this issue and fixed it?

**Comment by mjroeleveld** [comment]
@nickvarterian did you manage to fix this?

**Comment by kravetsone** [comment]
Really how to fix it?

**Comment by kravetsone** [comment]
> Really how to fix it?

I disabled web search and it fixed it
